# Generated by Django 6.0 on 2025-12-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
