# Generated by Django 6.0 on 2025-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0003_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishlistId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
